In [90]:
import pandas as pd
import os
import csv

In [136]:
alcohol_input_df = pd.read_excel('Data/Input/Alcohol.xlsx')
alcohol_input_df = alcohol_input_df[['State','Location', '2005 Both Sexes','2006 Both Sexes',
                                     '2007 Both Sexes','2008 Both Sexes','2009 Both Sexes', 
                                     '2010 Both Sexes', '2011 Both Sexes']]

In [143]:
alcohol_input_df.rename(columns = {'Location':'County', '2005 Both Sexes':'2005','2006 Both Sexes':'2006','2007 Both Sexes':'2007',
                                  '2008 Both Sexes':'2008','2009 Both Sexes':'2009','2010 Both Sexes':'2010',
                                  '2011 Both Sexes':'2011',}, inplace = True)

In [144]:
years = list(alcohol_input_df.columns)
years = years[2:]

      State          County  2005  2006  2007  2008  2009  2010  2011
0  National   United States   7.0   7.2   7.7   7.8   7.7   7.8   8.8
1   Alabama         Alabama   6.0   5.6   5.6   6.2   6.0   6.0   7.3
2   Alabama  Autauga County   6.2   5.6   5.6   6.0   5.7   5.8   6.9
3   Alabama  Baldwin County   9.0   8.4   8.4   9.1   8.6   8.7  10.4
4   Alabama  Barbour County   5.4   5.0   5.1   5.6   5.5   6.1   7.4

In [153]:
alcohol_clean_df = []
for year in years:
    input_df = alcohol_input_df[['County', 'State', year]]
    input_df['Year'] = year
    input_df['Alcohol'] = input_df[year]
    alcohol_clean_df.append(input_df[['County', 'State', 'Year', 'Alcohol']])
alcohol_clean_df = pd.concat(alcohol_clean_df)

/Users/Writoban/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/Writoban/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [154]:
alcohol_clean_df[alcohol_clean_df.County != 'United States']
alcohol_clean_df['County State'] = alcohol_clean_df['County']+' '+ alcohol_clean_df['State']
alcohol_clean_df.to_excel('Data/Output/AlcoholClean.xls')

In [177]:
pa_df = pd.read_csv('Data/Input/Physical Activity.csv')
pa_df.count()

County         18858
State          18858
fips           18852
merged_fips    18858
PA2001         18858
PA2002         12572
PA2003         18858
PA2004         12572
PA2005         18858
PA2006         12572
PA2007         18858
PA2008         12572
PA2009         18858
PA2010         12572
PA2011         18858
dtype: int64

In [176]:
pa_df.rename(columns = {'PA2005':'2005','PA2006':'2006','PA2007':'2007',
                        'PA2008':'2008','PA2009':'2009','PA2010':'2010','PA2011':'2011'},inplace=True)
pa_df = pa_df [['County', 'State', 'fips', 'merged_fips', '2005','2006','2007','2008','2009','2010','2011']]
pa_df.count()

County         18858
State          18858
fips           18852
merged_fips    18858
2005           18858
2006           12572
2007           18858
2008           12572
2009           18858
2010           12572
2011           18858
dtype: int64

In [169]:
pa_clean_df = []
for year in years:
    input_df = pa_df[['County', 'State', 'fips', 'merged_fips' , year]]
    input_df['Year'] = year
    input_df['Physical Activity'] = input_df[year]
    pa_clean_df.append(input_df[['County', 'State', 'fips','merged_fips', 'Year', 'Physical Activity']])
pa_clean_df = pd.concat(pa_clean_df)

        County    State    fips  merged_fips  Year  Physical Activity
0  Autauga, AL  Alabama  1001.0         1001  2005              77.21
1  Autauga, AL  Alabama  1001.0         1001  2005              67.60
2  Baldwin, AL  Alabama  1003.0         1003  2005              75.10
3  Baldwin, AL  Alabama  1003.0         1003  2005              75.62
4  Barbour, AL  Alabama  1005.0         1005  2005              65.43

In [171]:
pa_clean_df.to_csv('Data/Output/Physical Activity.csv')

In [180]:
df2 = pd.read_csv('Data/Input/Alabama.csv')
df2 = df2[['location_name','FIPS','sex_id','year_id','mx']]
years = ['2005','2006','2007','2008','2009','2010','2011']
d2 = df2[df2['year_id'].isin(years)]
df2 = df2.loc[df2['sex_id'] == 3]
df2 = df2.loc[df2['FIPS'] != 1]
df2.to_csv('Data/State/AL.csv')
df1=pd.read_csv('Data/State/AL.csv')
df2=pd.read_csv('Data/State/AZ.csv')
df3=pd.read_csv('Data/State/AR.csv')
df4=pd.read_csv('Data/State/CA.csv')
df5=pd.read_csv('Data/State/CO.csv')
df6=pd.read_csv('Data/State/CT.csv')
df7=pd.read_csv('Data/State/DE.csv')
df8=pd.read_csv('Data/State/DC.csv')
df9=pd.read_csv('Data/State/FL.csv')
df10=pd.read_csv('Data/State/GA.csv')
df11=pd.read_csv('Data/State/HI.csv')
df12=pd.read_csv('Data/State/ID.csv')
df13=pd.read_csv('Data/State/IL.csv')
df14=pd.read_csv('Data/State/IN.csv')
df15=pd.read_csv('Data/State/IA.csv')
df16=pd.read_csv('Data/State/KS.csv')
df17=pd.read_csv('Data/State/KY.csv')
df18=pd.read_csv('Data/State/LA.csv')
df19=pd.read_csv('Data/State/ME.csv')
df20=pd.read_csv('Data/State/MD.csv')
df21=pd.read_csv('Data/State/MA.csv')
df22=pd.read_csv('Data/State/MI.csv')
df23=pd.read_csv('Data/State/MN.csv')
df24=pd.read_csv('Data/State/MS.csv')
df25=pd.read_csv('Data/State/MO.csv')
df26=pd.read_csv('Data/State/MT.csv')
df27=pd.read_csv('Data/State/NE.csv')
df28=pd.read_csv('Data/State/NV.csv')
df29=pd.read_csv('Data/State/NH.csv')
df30=pd.read_csv('Data/State/NJ.csv')
df31=pd.read_csv('Data/State/NM.csv')
df32=pd.read_csv('Data/State/NY.csv')
df33=pd.read_csv('Data/State/NC.csv')
df34=pd.read_csv('Data/State/ND.csv')
df35=pd.read_csv('Data/State/OH.csv')
df36=pd.read_csv('Data/State/OK.csv')
df37=pd.read_csv('Data/State/OR.csv')
df38=pd.read_csv('Data/State/PA.csv')
df39=pd.read_csv('Data/State/RI.csv')
df40=pd.read_csv('Data/State/SC.csv')
df41=pd.read_csv('Data/State/SD.csv')
df42=pd.read_csv('Data/State/TN.csv')
df43=pd.read_csv('Data/State/TX.csv')
df44=pd.read_csv('Data/State/UT.csv')
df45=pd.read_csv('Data/State/VT.csv')
df46=pd.read_csv('Data/State/VA.csv')
df47=pd.read_csv('Data/State/WA.csv')
df48=pd.read_csv('Data/State/WV.csv')
df49=pd.read_csv('Data/State/WI.csv')
df50=pd.read_csv('Data/State/WY.csv')

pdList = [df1, df2,df3,df4,
df5,
df6,
df7,
df8,
df9,
df10,
df11,
df12,
df13,
df14,
df15,
df16,
df17,
df18,
df19,
df20,
df21,
df22,
df23,
df24,
df25,
df26,
df27,
df28,
df29,
df30,
df31,
df32,
df33,
df34,
df35,
df36,
df37,
df38,
df39,
df40,
df41,
df42,
df43,
df44,
df45,
df46,
df47,
df48,
df49,
df50]

new_df = pd.concat(pdList)
new_df.count()
new_df.to_csv('Data/Output/Cancer Mortality.csv')

/Users/Writoban/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:107: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [181]:
ff = pd.read_csv('Data/Input/Fast Food.csv')
ff_2007=ff[['FIPS','State','County','FF2007']]
ff_2007['Year'] = '2007'
ff_2007.rename(columns = {'FF2007':'FF'}, inplace = True)
ff_2009=ff[['FIPS','State','County','FF2009']]
ff_2009['Year'] = '2009'
ff_2009.rename(columns = {'FF2009':'FF'}, inplace = True)
ff_2011=ff[['FIPS','State','County','FF2011']]
ff_2011['Year'] = '2011'
ff_2011.rename(columns = {'FF2011':'FF'}, inplace = True)
ff_df = ff_2007.append(ff_2009, ignore_index=True)
ff_df = ff_df.append(ff_2011, ignore_index=True)
ff_df.to_csv('Data/Output/CleanFF.csv')

/Users/Writoban/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/Writoban/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Writoban/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':